# Generated by Django 4.2.13 on 2024-07-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_key_expired',
        ),
    ]
