# Generated by Django 4.2.13 on 2024-07-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_activation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_exceeding',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Сумма которой не хватает до превышения бюджета,после которой пользователь получит уведомление.', max_digits=12, verbose_name='Сумма до превышения'),
        ),
    ]
