# Generated by Django 4.2.13 on 2024-07-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_amount_exceeding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirming',
        ),
    ]
