# Generated by Django 4.2.13 on 2024-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность транзакции'),
        ),
    ]
