# Generated by Django 4.2.13 on 2024-07-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetingcategories',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Сумма покупок в данной категории в рублях'),
            preserve_default=False,
        ),
    ]
