# Generated by Django 4.2.13 on 2024-07-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_budgetingcategories_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetingcategories',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма покупок в данной категории в рублях'),
        ),
    ]
