# Generated by Django 4.2.13 on 2024-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_alter_budgetingcategories_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetingcategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
